spring.data.mongodb.uri=${MONGODB_URL}

spring.servlet.multipart.max-file-size=${UPLOAD_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${UPLOAD_MAX_REQUEST_SIZE}

######### Health check #########
management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=/strike-off-objections-api/healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true

server.port=${PORT:5009}
chs.api.key=${CHS_API_KEY}
chs.kafka.api.url=${CHS_KAFKA_API_URL}

email.subject=${EMAIL_SUBJECT}
email.senderAppId=${EMAIL_SENDER_APP_ID}
email.attachmentDownloadUrlPrefix=${EMAIL_ATTACHMENT_DOWNLOAD_URL_PREFIX}
email.submittedExternalTemplateMessageType=${EMAIL_SUBMITTED_EXTERNAL_TEMPLATE_MESSAGE_TYPE}
email.submittedInternalTemplateMessageType=${EMAIL_SUBMITTED_INTERNAL_TEMPLATE_MESSAGE_TYPE}
email.recipientsCardiff=${EMAIL_RECIPIENTS_CARDIFF}
email.recipientsEdinburgh=${EMAIL_RECIPIENTS_EDINBURGH}
email.recipientsBelfast=${EMAIL_RECIPIENTS_BELFAST}