spring.mongodb.uri=${MONGODB_URL}

spring.servlet.multipart.max-file-size=${UPLOAD_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${UPLOAD_MAX_REQUEST_SIZE}

management.endpoints.access.default=none
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=/strike-off-objections-api/healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.access=read_only

server.port=${PORT:5009}

chs.kafka.api.key=${CHS_INTERNAL_API_KEY}
chs.kafka.api.url=${CHS_KAFKA_API_URL}

email.subject=${EMAIL_SUBJECT}
email.senderAppId=${EMAIL_SENDER_APP_ID}
email.attachmentDownloadUrlPrefix=${EMAIL_ATTACHMENT_DOWNLOAD_URL_PREFIX}
email.submittedExternalTemplateMessageType=${EMAIL_SUBMITTED_EXTERNAL_TEMPLATE_MESSAGE_TYPE}
email.submittedInternalTemplateMessageType=${EMAIL_SUBMITTED_INTERNAL_TEMPLATE_MESSAGE_TYPE}
email.recipientsCardiff=${EMAIL_RECIPIENTS_CARDIFF}
email.recipientsEdinburgh=${EMAIL_RECIPIENTS_EDINBURGH}
email.recipientsBelfast=${EMAIL_RECIPIENTS_BELFAST}

file.transfer.service.url=${FILE_TRANSFER_SERVICE_URL}
internal.api.key=${CHS_INTERNAL_API_KEY}

# OpenTelemetry configuration
management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics